repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

-   repo: local
    hooks:
    -   id: tests
        name: Run tests
        entry: python -m tests
        language: python
        types: [python]
